### ISSUE TITLE
:sparkles: CI/CD 적용

### ISSUE THREAD

**Issue by subin195-09** [Yoowatney/cabi_admin-v2#2]
## 기능
- githubAction 으로 CI/CD 적용

## 상세 설명
- CI : eslint, prettier 적용 예정
- CD : 기존에는 없었기 때문에, 배포과정을 쉘로 만들어 바꿀 예정

**Comment by Yoowatney** [comment]
혹시 CI에 lint랑 코드포맷터가 포함되어있는 개념인건가요?? CI를 잘 몰라서 여쭤봅니다,,

**Comment by joohongpark** [comment]
@Yoowatney CI는 변경된 코드를 중앙 리포지토리에 통합하기 위한 작업인데
중앙 리포지토리에 통합시키기 전 변경된 소스코드에 대해 테스트가 필요하기 때문에 CI 내에 테스트가 포함되어 있어요.
자바스크립트나 타입스크립트는 lint나 코드 포맷터로 기존 코드와의 일관성을 유지하거나 에러를 유발할 만한 요소들을 감지하는 것으로 알고 있는데 이런 과정이 자바스크립트에서 빌드 테스트 중 하나가 되기 때문에 CI에 린트와 포매터가 포함되어 있습니다.

**Comment by joohongpark** [comment]
참고로 제가 기존 진행한 프로젝트에선 빌드 테스트, 단위 테스트, 통합 테스트, Lint 체크를 진행하였으며 포맷터는 설정하지 않았었어요
