### ISSUE TITLE
:sparkles: 실DB 연동 repository 

### ISSUE THREAD

**Issue by subin195-09** [Yoowatney/cabi_admin-v2#3]
## 기능
- DB연동 repository를 생성하였습니다.

## 상세 설명
- typeorm이 아닌 기존 mariadb 모듈을 활용하였습니다.

**Comment by Yoowatney** [comment]
한가지 질문이 있습니다
제가 본 커밋까지에는 .env를 인식할만한 패키지(`dotenv` or `@nestjs/config`)같은게 보이지 않는데, 혹시 이에 대한 대처가 되신걸까요??

**Comment by joohongpark** [comment]
@Yoowatney 제가 곧 커밋할 버전에 대해선 env를 인식할 수 있도록 말씀하신 부분 적용할 예정이에용

**Comment by Yoowatney** [comment]
8c6a14433921dcfabb5d4390152f983d612b7527

lent 라우터에서 getLentInfo에 대한 포팅을 완료했습니다.
이외 다른 커밋이 있는데 함수명 수정같은 사소한 사항이라 commit id는 가장 앞 번호만 남겼습니다.
더불어 어제 효스팍님, 주팍님과 admin의 기존 코드를 nest로 어떻게 포팅할건지 간단하게 이야기를 해봤는데, 최대한 기존 admin코드를 따라가는 식으로 하잔 건의가 나왔습니다.
아래는 크게 논의했던 2가지 입니다.

1. 레포지토리 디렉토리에 추상클래스 속 메서드는 `findAll`과 같이 typeORM의 패턴을 따라가기보단 기존 admin 코드에서 사용했던 `getLentInfo`와 같은 함수명을 그대로 사용하자.
2. admin코드에서 express 기준 컨트롤러에서 어떤 친구는 객체로 한 번 감싸서 리턴, 어떤 친구는 감싸지 않은 채 리턴과 같이 일관적이지 않은 사례가 몇몇 있는데 이는 추 후 리팩토링의 사항으로 빼놓고 우선은 admin 코드 포팅에 초점을 맞추자.

혹시 이해가 잘 안가시거나 다른 의견이 있으신 분은 커멘트나 슬랙방에 말씀해주세요!
